services:
  web:
    build:
      context: ./
    command: 
      - --addr=:8000 
      - --dsn=dev:dev@tcp(db:3306)/snippetbox?parseTime=true&collation=utf8mb4_unicode_ci
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0.28
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=snippetbox
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      start_period: 5s
      retries: 3
      interval: 15s
      timeout: 30s
    volumes:
      - type: bind
        source: ./sql
        target: /docker-entrypoint-initdb.d
