GET http://localhost:4000/user/signup

###

POST http://localhost:4000/user/signup
Content-Type: application/x-www-form-urlencoded

name=Bob
&email=bob@example.com
&password=validPa$$word
&csrf_token=z6Dtwn7D4hoQznXINrxGgl71tghe3Ikm4hTsvHfdsLB+RpRVt/cbuUl5BWCJDnoKnWuSYN0Kxg5R13c143BUHA==
